language: python
sudo: required

python:
  - '3.6'
  - '3.6-dev'
  - '3.7-dev'
  - 'nightly'
  - 'pypy'

matrix:
  allow_failures:
    - python: '3.6-dev'
    - python: '3.7-dev'
    - python: 'nightly'
    - python: 'pypy'

install:
  - bash .travis/install.sh

script:
  - bash .travis/test.sh
  - python setup.py bdist_wheel && ls dist/
